# Site settings
title: Open Data Science Initiative Thesis Projects
email: N.Lawrence@sheffield.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Project offerings from the Open Data Science Initiative
baseurl: "/dsiprojects" # the subpath of your site, e.g. /blog/
url: "http://opendsi.cc" # the base hostname & protocol for your site
types:
- name: bscproject
  title: Undergraduate and Masters Projects
- name: phdproject
  title: PhD Projects

# Build settings
markdown: kramdown
permalink: "/:categories/:title.html"
