# Site settings
title: ML@CL MPhil/Part III and Part II Projects
author:
  name: ML@CL
  github: mlatcl
description: > # this means to ignore newlines until "baseurl:"
  Project offerings from the Open Data Science Initiative
baseurl: "/projects" # the subpath of your site, e.g. /blog/
url: "http://mlatcl.github.io" # the base hostname & protocol for your site
types:
- name: bscproject
  title: Part II Projects
- name: bscproject
  title: Part III MPhil Projects
- name: phdproject
  title: PhD Projects

collections:
  projects:
    output: true
ghub:
  edit: true
  repository: projects
future: true
publisher: The Computer Laboratory

plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlatcl/bulmalawrennd/proceedings
style: mlatcl

analytics:
  google: 
    tracking_id: UA-184894912-1
future: true

# Build settings
markdown: kramdown
permalink: "/:categories/:title.html"
